plugins {
    id 'java'
}

dependencies {
    // ArchUnit
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.3.0'

    // Все модули — testImplementation, т.к. сканируются только в тестах
    testImplementation project(':backend:common')
    testImplementation project(':backend:iam')
    testImplementation project(':backend:jobs')
    testImplementation project(':backend:schedules')
    testImplementation project(':backend:executions')
    testImplementation project(':backend:secrets')
    testImplementation project(':backend:analytics')
    testImplementation project(':backend:orchestrator')
}

test {
    useJUnitPlatform()
}

jar.enabled = false