plugins {
    id 'java-library'
}

dependencies {
    api project(':backend:common')
    api project(':backend:jobs') // проверка существования Job
    
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.postgresql:postgresql'
    api 'org.flywaydb:flyway-core'
    
    // Для расчёта следующих запусков
    implementation 'com.cronutils:cron-utils'
    
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}