plugins {
    id 'java-library'
}

dependencies {
    // Внутренние модули
    api project(':backend:common')
    api project(':backend:jobs')          // для проверки существования Job и её организации
    api project(':backend:iam')          // для AuditPort и т.п., если понадобится

    // Spring Boot starters
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    // База
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.liquibase:liquibase-core'

    // Библиотеки для cron и времени
    implementation 'com.cronutils:cron-utils'

    // Сериализация
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // Ломбок
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Тесты (если нужно)
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}
