// ---------------------------------------------------------------------------
// Analytics types for CaaS dashboard
// ---------------------------------------------------------------------------

export interface SummaryResponse {
  totalExecutions: number;
  successfulExecutions: number;
  failedExecutions: number;
  cancelledExecutions: number;
  avgDurationMs: number;
  period: string;
  fromDate: string;
  toDate: string;
}

export interface PredictionItem {
  jobUuid: string;
  jobName: string;
  failureProbability: number; // 0-1
  expectedDurationMs: number;
  confidence: number; // 0-1
  nextExpectedRunAt: string; // ISO date
}

export interface PredictionsResponse {
  orgId: string;
  jobId?: string;
  predictions: PredictionItem[];
}

export type AnomalySeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface AnomalyItem {
  uuid: string;
  jobUuid: string;
  jobName: string;
  description: string;
  severity: AnomalySeverity;
  detectedAt: string; // ISO date
  relatedExecutionUuid?: string;
}

export interface AnomaliesResponse {
  orgId: string;
  jobId?: string;
  fromDate: string;
  toDate: string;
  anomalies: AnomalyItem[];
}

// ---------------------------------------------------------------------------
// Chart-specific data points (generated by mock)
// ---------------------------------------------------------------------------

export interface TimeSeriesPoint {
  date: string;
  success: number;
  failure: number;
}

export interface DurationBucket {
  bucket: string;
  count: number;
}
