plugins {
    id 'java-library'
}

dependencies {
    api project(':backend:common')
    api project(':backend:iam') // для проверки доступа
    
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.postgresql:postgresql'
    api 'org.flywaydb:flyway-core'
    
    // Шифрование (можно использовать JCA или специализированные библиотеки)
    implementation 'org.springframework.security:spring-security-crypto'
    
    // Для работы с временными токенами
    implementation 'io.jsonwebtoken:jjwt-api'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson'
}