plugins {
    id 'java-library'
}

dependencies {
    // Модули проекта
    api project(':backend:common')
    api project(':backend:iam')
    api project(':backend:jobs')

    // Spring
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-security'

    // БД
    api 'org.postgresql:postgresql'
    api 'org.liquibase:liquibase-core'

    // MinIO
    implementation 'io.minio:minio:8.5.17'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
