package com.cromp.notifications.domain.model;

public enum NotificationEventType {
    INVITATION_CREATED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_REVOKED,
    INVITATION_EXPIRED,

    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,

    JOB_EXECUTION_FAILED,
    JOB_EXECUTION_SUCCEEDED,
    JOB_DISABLED,
    JOB_EXECUTION_TIMEOUT,

    SECRET_EXPIRING,
    SECRET_ROTATED,

    BILLING_TRIAL_ENDING
}
